from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_DefaultRenderGraph():
    g = RenderGraph('DefaultRenderGraph')
    g.create_pass('VAO', 'VAO', {'kVaoRadius': 0.5, 'kVaoExponent': 2.0, 'kSampleCount': 8, 'resolutionDivisor': 4, 'enableGuardBand': True, 'SVAOInputMode': True, 'useRayInterval': True})
    g.create_pass('LinearizeDepth', 'LinearizeDepth', {})
    g.create_pass('NormalsToViewSpace', 'NormalsToViewSpace', {})
    g.create_pass('RTStochasticDepth', 'RTStochasticDepth', {'resolutionDivisor': 4, 'enableGuardBand': True})
    g.create_pass('SVAO', 'SVAO', {'kVaoRadius': 0.5, 'kVaoExponent': 2.0, 'kSampleCount': 8, 'resolutionDivisor': 4, 'enableGuardBand': True})
    g.create_pass('BilateralBlur', 'BilateralBlur', {'numIterations': 1, 'kernelSize': 2, 'betterSlope': True})
    g.create_pass('DeferredLighting', 'DeferredLighting', {'ambientLight': 0})
    g.create_pass('GBufferLite', 'GBufferLite', {})
    g.create_pass('CrossFade', 'CrossFade', {'outputFormat': 'RGBA32Float', 'enableAutoFade': False, 'waitFrameCount': 10, 'fadeFrameCount': 100, 'fadeFactor': 0.0})
    g.add_edge('NormalsToViewSpace.normalsViewOut', 'VAO.normalViewIn')
    g.add_edge('RTStochasticDepth.stochasticDepth', 'SVAO.stochDepthIn')
    g.add_edge('VAO.aoOut', 'SVAO.aoInOut')
    g.add_edge('VAO.aoMaskOut', 'SVAO.aoMaskIn')
    g.add_edge('NormalsToViewSpace.normalsViewOut', 'SVAO.normalViewIn')
    g.add_edge('SVAO.aoInOut', 'BilateralBlur.colorIn')
    g.add_edge('VAO.rayMinOut', 'RTStochasticDepth.rayMinIn')
    g.add_edge('VAO.rayMaxOut', 'RTStochasticDepth.rayMaxIn')
    g.add_edge('VAO', 'RTStochasticDepth')
    g.add_edge('RTStochasticDepth', 'SVAO')
    g.add_edge('BilateralBlur.colorOut', 'DeferredLighting.ambientOcclusion')
    g.add_edge('GBufferLite.depth', 'LinearizeDepth.depthIn')
    g.add_edge('GBufferLite.normW', 'NormalsToViewSpace.normalsWorldIn')
    g.add_edge('GBufferLite.posW', 'DeferredLighting.posW')
    g.add_edge('GBufferLite.normW', 'DeferredLighting.normW')
    g.add_edge('GBufferLite.diffuseOpacity', 'DeferredLighting.diffuseOpacity')
    g.add_edge('GBufferLite.specRough', 'DeferredLighting.specRough')
    g.add_edge('LinearizeDepth.linearDepthOut', 'CrossFade.A')
    g.add_edge('CrossFade.out', 'SVAO.linearDepthIn')
    g.add_edge('CrossFade.out', 'RTStochasticDepth.linearDepthIn')
    g.add_edge('CrossFade.out', 'VAO.linearDepthIn')
    g.add_edge('GBufferLite.linearDepth', 'CrossFade.B')
    g.add_edge('CrossFade.out', 'BilateralBlur.linearDepthIn')
    g.mark_output('DeferredLighting.kColorOut')
    g.mark_output('BilateralBlur.colorOut')
    return g

DefaultRenderGraph = render_graph_DefaultRenderGraph()
try: m.addGraph(DefaultRenderGraph)
except NameError: None
